# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 10 # jekyll-paginate > Blog post items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: Peggy Bockwinkel # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Peggy Bockwinkel # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    #- https://twitter.com/PeggyBockwinkel
    #- https://www.facebook.com/daviddarnes
    #- https://www.linkedin.com/in/daviddarnes
    - https://github.com/bockwinkel/villaruhla
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Projekte & Neues aus der Villa Ruhla # Needed for Siteleaf
    output: true
    description: "Es geht voran - Schritt für Schritt. Das Abenteuer Villa Ruhla aus verschiedenen Perspektiven. Mal unterhaltsam, mal kalkulierend, mal scheiternd, mal lustig, ... und immer authentisch." # The post list page content
    feature_text: |
      
    feature_image: "/assets/Ansichten_Sued-West_Website3.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/Ansichten_Sued-West_Website2.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: german # Set the site language
title: "Villa Ruhla" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Sei dabei beim Abenteuer Villa Ruhla! Genieße Geschichten rund um die Villa Ruhla. Projekte, die in der Villa Ruhla erträumt und umgesetzt werden. Begegnungen, die hier stattfinden. Immer authentisch. Immer mit Leib und Seele." # Site description and default description, also used in jekyll-seo-tag
url: "https://villaruhla.de" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/bockwinkel/villaruhla"
email: "willkommen@villaruhla.de"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation [Titel kann man hier an dieser Stelle anpassen. Die url muss aber an anderer Stelle noch angepasst werden. Hier nicht ändern.]
navigation_header:
- title: Home
  url: /
- title: Backstage
  url: /backstage/
- title: Blog
  url: /blog/
- title: Mehr Villa Ruhla
  url: https://instagram.com/villaruhla.de/
- title: Kategorien
  url: /kategorien/
- title: Suche
  url: /suche/
- title: Impressum
  url: /impressum/ 

navigation_footer:
- title: Created by David Darnes, adapted by Peggy Bockwinkel
  url: https://github.com/daviddarnes

# social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/PeggyBockwinkel
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # [Footer in den Blog-Posts.] Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  # Twitter: "#0d94e7"
  # facebook: "#3B5998"
  Verschicke diesen Post per Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
